server:
  port: 9060

spring:
  application:
    name: cereebro-server-eureka-addon
  jackson:
    serialization:
      indent_output: true
  freemarker:
    prefer-file-system-access: false

# Eureka Server : Standalone mode
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      # won't be used
      defaultZone: http://localhost:${server.port}/eureka

cereebro:
  server:
    system:
      name: cereebro-sample-system
