server:
  port: 9063

spring:
  application:
    name: cereebro-sample-netflix-app2
  jackson:
    serialization:
      indent_output: true

info:
  description: Second Sample Application using the Cereebro Snitch for Spring Cloud Netflix
