server:
  port: 9090
spring:
  application:
    name: cereebro-server
  thymeleaf:
    cache: false
  jackson:
    serialization:
      indent_output: true

cereebro:
  server:
    system:
      name: marvel
